[workspace]
resolver = "2"
members = [
    "crates/kamura",
    "crates/kamura-integrator", "crates/kamura-operator",
    "crates/kamura-runner",
    "crates/sayaka"
]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["B1ACK917"]
