[package]
name = "kamura-controller"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
sayaka = { path = "../sayaka" }
kamura-core = { path = "../kamura-core" }
redis = "0.26.1"
